Update guiutil.py
set_text expects a string while text sometimes can be of dbus.Int32 (not sure if bug from dbus or wicd-gtk but this fixes it).

  File "/usr/share/wicd/gtk/guiutil.py", line 165, in set_text
    self.entry.set_text(text)
TypeError: Gtk.Entry.set_text() argument 1 must be string, not dbus.Int32